<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="MAIN_simu" Id="{6437416a-b1ab-491b-b227-e4a8ab9af743}">
    <Declaration><![CDATA[
PROGRAM MAIN_simu
VAR
    simIO : MNG_Simulation;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Update IOs with simulation
simIO(bEnable := TRUE);

// Application code follows here:


]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>